[project]
name = "release-protect-authenticator"
authors = ["Release Protect Team"]
description = "A decentralized access management and release protection system"
telemetry = false
requirements = []
[contracts.release-protect]
path = "contracts/release-protect-authenticator.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
